spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5432/carefusion_development
    username: postgres
    password: carefusion
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  banner:
    location: banner.txt

server:
  port: 8080
