spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5432/carepulse_development
    username: carepulse_admin
    password: carepulse
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
